### ISSUE TITLE
Error: invalid byte sequence in UTF-8 - Failed to build on OSX 12.7.5

### ISSUE THREAD

**Issue by klaborda** [Morantron/homebrew-tmux-fingers#1]
Hello!  I'm trying to install this formula on my laptop (OSX 12.7.5) and it's failing with the following error.  Any ideas on what might be going on?  I wanted to ask here first before going to the brew issue track (per [their TS docs](https://docs.brew.sh/Troubleshooting)).

```
==> Fetching morantron/tmux-fingers/tmux-fingers
==> Downloading https://github.com/Morantron/tmux-fingers/archive/refs/tags/2.1.5.tar.gz
==> Downloading from https://codeload.github.com/Morantron/tmux-fingers/tar.gz/refs/tags/2.1.5
#=#=- #     #
==> Installing tmux-fingers from morantron/tmux-fingers
Error: invalid byte sequence in UTF-8
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:170:in `[]'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:170:in `block in keychain_username_password'
/usr/local/Homebrew/Library/Homebrew/utils/uid.rb:8:in `drop_euid'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:162:in `keychain_username_password'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:184:in `credentials'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:240:in `open_rest'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:148:in `private_repo?'
/usr/local/Homebrew/Library/Homebrew/tap.rb:361:in `private?'
/usr/local/Homebrew/Library/Homebrew/tap.rb:996:in `should_report_analytics?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:425:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:237:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:301:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `each'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:297:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

For related information...
`brew config` =>
```
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 6 days ago
Core tap JSON: 13 Jul 18:56 UTC
Core cask tap JSON: 13 Jul 18:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

and `brew doctor` => 
```
Your system is ready to brew.
```

**Comment by klaborda** [comment]
Just one update here... I was able to `brew install crystals` and build from the source, so... I guess that's good at least!  I love the plugin (using it on my work laptop where it works great).

Just not sure why the formula failed at this point.

**Comment by Morantron** [comment]
Hey! It looks like an issue on brew's end. That particular function seems to be in the [brew repo](https://github.com/Homebrew/brew/blob/8f863199bc7536789b19a068947199f5860aa308/Library/Homebrew/utils/github/api.rb#L161), so I would open an issue in that repo.

Glad that at least building from source works for you! 🙏
